### ISSUE TITLE
Location ID matching China Province ID

### ISSUE THREAD

**Issue by forloopkilla** [yg2619/Choropleth-Maps-in-Python#1]
Hi yg2619,

I have been trying to reproduce your code to my own dataset. Apparantly, the [repository](https://github.com/deldersveld/topojson/tree/master/countries/china) is does not have an 'ID' so I don't know what to match the Province name to. Perhaps it would be helpful to put the 'geo = pd.read_csv('Geography.csv')' file on here to, just so that we can reproduce the image?

Please advise,

forloopkilla15

**Comment by yirogue** [comment]
Hi forloopkilla,

I just uploaded the Geography.csv file and a notebook version of the codes so that you can see more clearly how this would work. 
You're right, this [repository](https://github.com/deldersveld/topojson/tree/master/countries/china) does not have an ID because setting the 'ID' in the geojson file is actually one of the things that you have to do it yourself when you are converting the topojson file. I have to say that while the codes to create the map is simple, the preparation of the geojson file is not that straightforward. In this case, I didn't use the topojson file in this [repository](https://github.com/deldersveld/topojson/tree/master/countries/china) cause it doesn't contain Taiwan so I have to combine several ones together instead. I have also uploaded the geojson file of China that I created and you can feel free to use it. 

I hope this is helpful.

yg2619
